# Generated by Django 2.2.7 on 2020-01-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
                ('class_str', models.CharField(max_length=5)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='photos/')),
            ],
        ),
    ]
