# Generated by Django 2.2.7 on 2020-01-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceAppBackend', '0002_photo_photo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
                ('class_str', models.CharField(max_length=5)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('photo_id', models.IntegerField(default=0)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
