# Generated by Django 2.2.7 on 2020-01-05 16:14

from django.db import migrations, models
import faceAppBackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('faceAppBackend', '0004_remove_image_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=faceAppBackend.models.get_upload_path),
        ),
    ]
